title: Station of Commons
options:
  changeTitle:
    admin: true
    editor: false
tabs:
  content:
    sections:
      drafts_events:
        extends: sections/events
        headline: Unpublished events
        status: draft
      unlisted_events:
        extends: sections/events
        headline: Events in review
        status: unlisted
      listed_events:
        extends: sections/events
        headline: Published events
        status: listed

  peers:
    sections:
      drafts:
        extends: sections/peers
        headline: Unpublished events
        status: draft
      unlisted:
        extends: sections/peers
        headline: Events in review
        status: unlisted
      listed:
        extends: sections/peers
        headline: Published events
        status: listed

  pages:
    sections:
        pages:
          type: pages
          create: default
          templates:
            - about
            - home
            - default

  matomo:
    label: Analytics
    icon: chart
    columns:
      - width: 3/4
        sections:
          main:
            type: matomo-main
      - width: 1/4
        sections:
          sidebar:
            type: matomo-sidebar
            link: false
