title: Station of Commons
options:
  changeTitle:
    admin: true
    editor: false
columns:
  - width: 1/2
    sections:
      drafts:
        extends: sections/events
        headline: Unpublished events
        status: draft
      unlisted:
        extends: sections/events
        headline: Events in review
        status: unlisted
      listed:
        extends: sections/events
        headline: Published events
        status: listed
  - width: 1/2
    sections:
      notes: sections/notes
      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
